roles:
  - c-cpp-dev: -, skills/cpp-dev; skills/c-dev, -skills/jni-master # тут в одну строку сбросили все предыдущие скилы для роли, и добавили skills/cpp-dev и skills/c-dev
  - c-cpp-no-java-dev: skills/cpp-dev; skills/c-dev, -skills/jni-master # тут только добавили skills/cpp-dev и skills/c-dev
  - uni-tester:
    - - # Сбрасываем все предыдущие скилы для роли (а это будет валидно в yml?)
    - skills/auto-tester
    - skills/manual-tester
  - super-architect:
    - sw-architect # Архитектор ПО
    - sys-architect # Архитектор всей системы
